USE bd_recrea_sys;
INSERT INTO componente (tipo, nombre, precio) VALUES
('Ensamblador', 'Monitor LED 32" Pantalla Táctil', 250.00),
('Ensamblador', 'Placa Base Arcade Pro V2', 220.00),
('Ensamblador', 'Joystick Industrial con Botones RGB', 55.00),
('Ensamblador', 'Fuente de Alimentación 600W Certificada', 95.00),
('Ensamblador', 'Kit Cableado Premium con Conectores Dorados', 35.00),
('Ensamblador', 'Tarjeta Gráfica Arcade 4GB', 180.00),
('Ensamblador', 'Sistema de Refrigeración Liquida', 120.00),
('Ensamblador', 'Panel de Control con 8 Botones', 45.00),
('Ensamblador', 'Convertidor de Video HDMI a VGA', 30.00),
('Ensamblador', 'Kit de Montaje Completo para Arcade', 75.00),
('Ensamblador', 'Cable HDMI Premium 2m', 12.00),
('Ensamblador', 'Adaptador USB a DB9', 8.50),
('Ensamblador', 'Altavoces estéreo USB', 25.00),
('Ensamblador', 'RAM DDR4 8GB Kit', 45.00),
('Ensamblador', 'Disco SSD 240GB', 55.00),
('Ensamblador', 'Procesador Intel i3', 110.00),
('Ensamblador', 'Procesador AMD Ryzen 3', 115.00),
('Ensamblador', 'Módulo Wi-Fi integrado', 20.00),
('Ensamblador', 'Módulo Bluetooth 5.0', 15.00),
('Ensamblador', 'Receptor IR para mandos', 10.00),
('Ensamblador', 'Teclado numérico auxiliar', 18.00),
('Ensamblador', 'Panel LED de señalización', 22.00),
('Ensamblador', 'Monitor secundario 7\"', 60.00),
('Ensamblador', 'Amplificador de audio 20W', 35.00),
('Ensamblador', 'Tarjeta de sonido 5.1', 40.00),
('Ensamblador', 'Módulo de iluminación RGB', 28.00),
('Ensamblador', 'Sensor de proximidad IR', 12.00),
('Ensamblador', 'Módulo de cámara VGA', 30.00),
('Ensamblador', 'Batería de respaldo 5V', 14.00),
('Ensamblador', 'Kit tornillería acero M3', 16.00);

INSERT INTO componente (tipo, nombre, precio) VALUES
('Mantenimiento', 'Kit Reparación Premium 50 Piezas', 50.00),
('Mantenimiento', 'Lubricante Industrial Especial', 25.00),
('Mantenimiento', 'Set Limpieza Profesional para Arcade', 30.00),
('Mantenimiento', 'Pasta Térmica de Alto Rendimiento', 15.00),
('Mantenimiento', 'Kit de Reparación para Pantallas', 60.00),
('Mantenimiento', 'Repuestos para Joysticks (Pack 10)', 20.00),
('Mantenimiento', 'Botones de Reemplazo RGB (Pack 20)', 35.00),
('Mantenimiento', 'Ventiladores de Refrigeración 120mm', 18.00),
('Mantenimiento', 'Cintas Aislantes y Termorretráctiles', 12.00),
('Mantenimiento', 'Kit Emergencia para Fuentes', 40.00),
('Mantenimiento', 'Fusible rápido 5A', 2.50),
('Mantenimiento', 'Fusible rápido 3A', 2.00),
('Mantenimiento', 'Conector de repuesto HDMI', 5.00),
('Mantenimiento', 'Switch de encendido', 7.00),
('Mantenimiento', 'Panel de botones recambio', 12.00),
('Mantenimiento', 'Cable de alimentación IEC', 6.00),
('Mantenimiento', 'Taco antivibración de goma', 4.00),
('Mantenimiento', 'Correa para ventilador', 3.50),
('Mantenimiento', 'Soporte metálico para placa', 9.00),
('Mantenimiento', 'Sensor térmico NTC', 8.00),
('Mantenimiento', 'Disipador con ventilador', 14.00),
('Mantenimiento', 'Resistencia 10 Ω', 1.50),
('Mantenimiento', 'Condensador 1000 µF', 2.00),
('Mantenimiento', 'Diodo rectificador (5 pz)', 4.00),
('Mantenimiento', 'LED recambio (pack 20)', 6.00),
('Mantenimiento', 'Conector Molex 4 pines', 3.50),
('Mantenimiento', 'Adaptador DC Jack', 5.50),
('Mantenimiento', 'Cinta térmica Kapton', 7.50),
('Mantenimiento', 'Pata ajustable para carcasa', 6.00),
('Mantenimiento', 'Estuche porta-fusibles', 8.00);
INSERT INTO componente (tipo, nombre, precio) VALUES
('Logistico', 'Carcasa Arcade Clásica Roja', 150.00),
('Logistico', 'Carcasa Arcade Premium Negra', 200.00),
('Logistico', 'Carcasa Arcade Deluxe con Iluminación', 250.00),
('Logistico', 'Carcasa Compacta para Espacios Pequeños', 120.00),
('Logistico', 'Carcasa Resistente para Exteriores', 180.00),
('Logistico', 'Carcasa Arcade Infantil (Colores Varios)', 130.00),
('Logistico', 'Carcasa Profesional para Torneos', 220.00),
('Logistico', 'Carcasa Móvil con Ruedas', 170.00),
('Logistico', 'Carcasa Personalizable (Base Blanca)', 160.00),
('Logistico', 'Carcasa Arcade XL para 2 Jugadores', 300.00);